spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name : gestion_des_soins
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}

    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
sftp :
  port : ${SFTP_PORT}
  host : ${SFTP_HOST}
  username: ${SFTP_USER}
  password: ${SFTP_PASS}
server:
  port: ${SERVER_PORT:8070}
