spring:
  devtools:
    restart:
      enabled: true
  application:
    name : gestion_des_soins
  datasource:
    url: jdbc:mysql://localhost:3306/hopital_pfe
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: anass.debbaghi123@gmail.com
    password: wxhkrooxdflsgmik

    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
sftp :
  port : 22
  host : localhost
  username : anass
  password : anass
  remoteImagesDirectory : /media
  remoteFilesDirectory : /media
  localDirectory : /uploads
server:
  port: 8070
#  address: 192.168.1.116

