spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
  application:
    name : gestion_des_soins
  datasource:
    url: jdbc:mysql://localhost:3306/hopital_pfe
    username: anass
    password: anass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: anass.debbaghi123@gmail.com
    password: wxhkrooxdflsgmik

    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
sftp :
  port : 21
  host : localhost
  username: anass
  password: '0000'
server:
  port: 8070
  address: 0.0.0.0
