package com.fsdm.hopital.exceptions;

public enum ProcessingException {
    USER_NOT_AVAILABLE_AT_THIS_TIME,
    USER_NOT_FOUND,
    TOKEN_NOT_FOUND,
    INVALID_USERNAME_PASSWORD,
    INVALID_USER_DETAILS,
    EMAIL_ALREADY_EXISTS,
    INVALID_PASSWORD,
    USER_NOT_SAVED,
    INTERNAL_ERROR,
    INVALID_OPERATON

}
